apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  volumes:
    - name: hostpath-vol
      hostPath:
        path: /var/tmp
  containers:
    - name: hostpath-pod
      image: "k8s.gcr.io/busybox"
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
      command:
        [
          "/bin/sh",
          "-c",
          "echo Hello Team, This is Sample File for HostVolume - $(date) >> /output/output.txt",
        ]
      volumeMounts:
        - name: hostpath-vol
          mountPath: /output
