apiVersion: v1
kind: Pod
metadata:
  name: my-pv-pod
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: busybox
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
      command:
        [
          "sh",
          "-c",
          "echo Hello Team, This is Persistnent Volume Claim >> /output/success.txt",
        ]
      volumeMounts:
        - mountPath: /output
          name: my-pv
  volumes:
    - name: my-pv
      persistentVolumeClaim:
        claimName: my-pvc
