apiVersion: v1
kind: Pod
metadata:
  name: frontend-1
spec:
  containers:
    - name: app
      image: alpine
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
      command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-2
spec:
  containers:
    - name: app
      image: alpine
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
      command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-3
spec:
  containers:
    - name: app
      image: alpine
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
      command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-4
spec:
  containers:
    - name: app
      image: alpine
      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
      command: ["sleep", "3600"]
